name: teenguard-env
channels:
  - defaults
dependencies:
  - python=3.8  # or any version you are using
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - yellowbrick
  - imbalanced-learn
  - pip
  - pip:
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - scikit-learn
    - yellowbrick
    - imbalanced-learn
